<ips:template parameters="$member, $check" />

{{if $check}}
<ul class='ipsButton_split' style='position: absolute; left: 10px; top: 10px; z-index: 2000;' data-hideOnCoverEdit>
	<li>
		<a href='{url="app=core&module=members&controller=profile&do=change&id={$member->member_id}"}' class='ipsButton ipsButton_overlaid' data-ipsDialog data-ipsDialog-modal='true' data-ipsDialog-title='{lang="f_change_group"}'>
			<i class='fa fa-pencil'></i>&nbsp;<span class='ipsResponsive_hidePhone ipsResponsive_inline'>&nbsp;&nbsp;{lang="f_change_group"}</span>
		</a>
	</li>
</ul>
{{endif}}
