<ips:template parameters="$request" />
{template="includeCSS" app="core" group="global" location="global" params=""}
<style>body { background: #fff none; }</style><br><br><br><br>
<div class="ipsPrint">

	<div class="ipsType_center ipsSpacer_bottom ipsSpacer_top">
		<h1 class="ipsType_veryLarge ipsType_reset">Карточка заявки #{$request->id}</h1>
	</div>

	<table class="ipsTable ipsTable_responsive ipsTable_zebra">
		<thead>
			<tr class="ipsAreaBackground">
				<th style="color: 000000;">Поле</th>
				<th style="color: 000000;">Значение</th>
			</tr>
		</thead>
		<tbody data-role="tableRows">
			{{foreach array( 'id', 'name', 'type', 'released', 'condition', 'firstname', 'lastname', 'middlename', 'email', 'skype', 'phone', 'phone_extra', 'phone_mobile', 'country', 'region', 'city', 'company', 'companydetails', 'info', 'request_member', 'request_email', 'request_ipaddress', 'request_status', 'request_created', 'request_assigned', 'request_locked', 'manufacturer', 'request_coupon', 'request_plan', 'request_comment', 'request_viewed_by', 'resolve_price', 'resolve_comment', 'resolve_autoreport', 'resolve_info' ) as $row}}
				<tr>
					<td>{lang="valuation_field_r_$row"}</td>
					<td>
						{{if $row == 'request_status'}}{lang="valuation_status_{$request->$row}"}</td></tr>{{continue;}}{{endif}}
						{{if $row == 'resolve_autoreport'}}{lang="resolve_autoreport_{$request->$row}"}</td></tr>{{continue;}}{{endif}}
						{{if $row == 'type' or $row == 'manufacturer' or $row == 'country'}}{lang="valuation_{$row}_{$request->$row}"}{{else}}{$request->$row|raw}{{endif}}					
					</td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>

</div> 