<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-tableID='requests' data-controller='core.global.core.table(tracker.requestTable){{if \IPS\Member::loggedIn()->currentRole()}},core.front.core.moderation{{endif}}'>

{{if member.valCan( 'use_filter' )}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<aside class='ipsColumn ipsColumn_wide'>
			<div class='ipsAreaBackground_light ipsPad_half' >
				<div class='ipsSideMenu ipsSpacer_top ipsSpacer_half' id='elSupport_menu' data-ipsSideMenu data-ipsSideMenu-type='check'>
					{{if \IPS\Member::loggedIn()->currentRole()}}
						<h3 class='ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium'>
							<a href='#elSupport_menu' class='ipsPad_double' data-action='openSideMenu'><i class='fa fa-bars'></i> &nbsp;{lang="valuation_request_filters"}&nbsp;<i class='fa fa-caret-down'></i></a>
						</h3>

						<h4 class='ipsSideMenu_title'>{lang="valuation_request_filters"}</h4>
						<ul class='ipsSideMenu_list ipsSideMenu_withChecks'>
							<li data-action="tableFilter" data-filter="" data-support-filter="assigned" class='ipsSideMenu_item {{if request.assigned}}ipsSideMenu_itemActive{{endif}}' data-ipsMenuValue=''>
								<a href='{$table->baseUrl->setQueryString( 'assigned', '1' )}'>{lang="valuation_filter_assigned_to_me"}</a>
							</li>
						</ul>
					{{endif}}

					{{$myFilters = \IPS\valuation\Tracker\Request::myFilters();}}
					<h4 class='ipsSideMenu_title'>{lang="valuation_statuses"}</h4>
					<ul class='ipsSideMenu_list ipsSideMenu_withChecks'>
						{{foreach \IPS\valuation\Tracker\Request::statusesToFilterBy() as $status}}
							{{if \IPS\Member::loggedIn()->currentRole() != 'admin' and $status == 'drft'}}{{continue;}}{{endif}}
							<li class="ipsSideMenu_item {{if in_array( $status, $myFilters['statuses'] )}}ipsSideMenu_itemActive{{endif}}" data-type='status' data-ipsMenuValue='{$status}'>
								<a href="{$table->baseUrl->setQueryString( array( 'statuses' => $status ) )}">
									{{if \IPS\Member::loggedIn()->currentRole()}}
										{lang="valuation_status_{$status}"}
									{{else}}
										{lang="valuation_status_{$status}_client"}
									{{endif}}
								</a>
							</li>
						{{endforeach}}
					</ul>
				</div>
			</div>
		</aside>
		<section class='ipsColumn ipsColumn_fluid'>
{{endif}}

{{if $quickSearch !== NULL or $table->advancedSearch or !empty( $table->filters )}}
	<div class='ipsClearfix ipsClear ipsPad acpWidgetToolbar ipsAreaBackground_dark' data-role="tableSortBar">
		{{if $quickSearch !== NULL or $table->advancedSearch}}
			{{if $table->advancedSearch}}
				<a class='ipsPos_right acpWidgetSearch' data-ipsTooltip aria-label='{lang="search"}' href='{$table->baseUrl->setQueryString( array( 'advancedSearchForm' => '1', 'filter' => $table->filter, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection ) )}' data-ipsDialog data-ipsDialog-title='{lang="search"}'><i class='fa fa-cog'></i></a>
			{{endif}}
			{{if $quickSearch !== NULL}}
				<input type='text' class='ipsField_short ipsPos_right acpTable_search ipsJS_show' data-role='tableSearch' results placeholder="{{if is_string( $quickSearch )}}{lang="search_prefix" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $table->langPrefix . $quickSearch )"}{{else}}{lang="search"}{{endif}}" value="{expression="\IPS\Request::i()->quicksearch"}">
			{{endif}}
		{{endif}}
	</div>

	<div class='ipsButtonBar ipsClearfix ipsPad_half'>
		<ul class='ipsButtonRow ipsPos_right ipsClearfix'>
			<li>
				<a href='#elSortMenu_menu' id='elSortMenu' data-ipsMenu data-ipsMenu-activeClass='ipsButtonRow_active' data-ipsMenu-selectable="radio">{lang="sort_by"} <i class='fa fa-caret-down'></i></a>
				<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' id='elSortMenu_menu'>
					{{foreach array( 'r_id', 'r_released', 'r_request_created', 'r_request_updated', 'r_resolve_price', 'r_request_gallerysize' ) as $val}}
						<li class='ipsMenu_item {{if $val == str_replace( 'sev_position asc, ', '', $table->sortBy )}}ipsMenu_itemChecked{{endif}}' data-ipsMenuValue="{$val}">
							<a href='{$table->baseUrl->setQueryString( array( 'sortby' => $val ) )}'>{lang="valuation_sortby_$val"}</a>
						</li>
					{{endforeach}}
				</ul>
			</li>
			<li>
				<a href='#elOrderMenu_menu' id='elOrderMenu' data-ipsMenu data-ipsMenu-activeClass='ipsButtonRow_active' data-ipsMenu-selectable="radio">{lang="order_by"} <i class='fa fa-caret-down'></i></a>
				<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' id='elOrderMenu_menu'>
					<li class='ipsMenu_item {{if $table->sortDirection == 'asc'}}ipsMenu_itemChecked{{endif}}' data-ipsMenuValue='asc'>
						<a href='{$table->baseUrl->setQueryString( array( 'sortdirection' => 'asc' ) )}'>{lang="ascending"}</a>
					</li>
					<li class='ipsMenu_item {{if $table->sortDirection == 'desc'}}ipsMenu_itemChecked{{endif}}' data-ipsMenuValue='desc'>
						<a href='{$table->baseUrl->setQueryString( array( 'sortdirection' => 'desc' ) )}'>{lang="descending"}</a>
					</li>
				</ul>
			</li>
		</ul>
		{{if $table->pages > 1}}
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
			</div>
		{{endif}}
	</div>
{{endif}}

{{if \IPS\Member::loggedIn()->currentRole()}}
	<form action="{$table->baseUrl->csrf()}" method="post" data-role='moderationTools' data-ipsPageAction>
{{endif}}
	<div data-role="extraHtml">{$table->extraHtml|raw}</div>
	<table class='ipsTable ipsTable_responsive ipsTable_zebra {{foreach $table->classes as $class}}{$class} {{endforeach}}'>
		<thead>
			<tr class='ipsAreaBackground'>
				<th>&nbsp;</th>
				<th>Заявка</th>
				<th>Тип</th>
				<th>Создал</th>
				<th>Статус</th>
				<th>Оценка, руб.</th>
				{{if \IPS\Member::loggedIn()->currentRole()}}<th>Оценщик</th>{{endif}}
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody data-role="tableRows" id="#elTable_{$table->uniqueId}">
			{{if count( $rows )}}
				{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
			{{endif}}
		</tbody>
	</table>

{{if \IPS\Member::loggedIn()->currentRole()}}
	<div class="ipsAreaBackground ipsPad ipsClearfix" data-role="pageActionOptions">
		<div class="ipsPos_right">
			<select name="modaction" data-role="moderationAction">
				<optgroup label="{lang="valuation_mod_status"}" data-action='status'>
					{{if $table->canModerate('drft')}}
						<option value='drft'>{lang="valuation_status_drft"}</option>
					{{endif}}
					{{if $table->canModerate('rcvd')}}
						<option value='rcvd'>{lang="valuation_status_rcvd"}</option>
					{{endif}}
					{{if $table->canModerate('open')}}
						<option value='open'>{lang="valuation_status_open"}</option>
					{{endif}}
					{{if $table->canModerate('clsd')}}
						<option value='clsd'>{lang="valuation_status_clsd"}</option>
					{{endif}}
					{{if $table->canModerate('frzn')}}
						<option value='frzn'>{lang="valuation_status_frzn"}</option>
					{{endif}}
					{{if $table->canModerate('reop')}}
						<option value='reop'>{lang="valuation_status_reop"}</option>
					{{endif}}
					{{if $table->canModerate('rmvd')}}
						<option value='rmvd'>{lang="valuation_status_rmvd"}</option>
					{{endif}}
					{{if $table->canModerate('hddn')}}
						<option value='hddn'>{lang="valuation_status_hddn"}</option>
					{{endif}}
				</optgroup>
			</select>
			<button type="submit" class="ipsButton ipsButton_alternate ipsButton_verySmall">{lang="submit"}</button>
		</div>
	</div>
</form>
{{endif}}

{{if $table->pages > 1}}
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		<div data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit, TRUE, $table->getPaginationKey()"}
		</div>
	</div>
{{endif}}

{{if member.valCan( 'use_filter' )}}
		</section>
	</div>
{{endif}}