<ips:template parameters="" />
{{if ( \IPS\Settings::i()->site_online || \IPS\Member::loggedIn()->group['g_access_offline'] ) and ( \IPS\Dispatcher::i()->application instanceof \IPS\Application AND \IPS\Dispatcher::i()->application->canAccess() )}}
<ul class='ipsList_inline ipsType_center ipsSpacer_top' id="elFooterLinks">

	{{$languages = \IPS\Lang::getEnabledLanguages();}}
	{{if count( $languages ) > 1}}
		<li>
			<a href='#elNavLang_menu' id='elNavLang' data-ipsMenu data-ipsMenu-above>{lang='language'} <i class='fa fa-caret-down'></i></a>
			<ul id='elNavLang_menu' class='ipsMenu ipsMenu_selectable ipsHide'>
			{{foreach $languages as $id => $lang }}
				<li class='ipsMenu_item{{if \IPS\Member::loggedIn()->language()->id == $id || ( $lang->default && \IPS\Member::loggedIn()->language === 0 )}} ipsMenu_itemChecked{{endif}}'>
					<form action="{url="app=core&module=system&controller=language" noprotocol="true" csrf="true" seoTemplate="language"}" method="post">
					<button type='submit' name='id' value='{$id}' class='ipsButton ipsButton_link'>{{if $lang->get__icon()}}<i class='{$lang->get__icon()}'></i> {{endif}}{$lang->title} {{if $lang->default}}{lang="default"}{{endif}}</button>
					</form>
				</li>
			{{endforeach}}
			</ul>
		</li>
	{{endif}}
	{{$themes = \IPS\Theme::getThemesWithAccessPermission();}}
	{{if count ( $themes ) > 1 }}
		<li>
			<a href='#elNavTheme_menu' id='elNavTheme' data-ipsMenu data-ipsMenu-above>{lang='skin'} <i class='fa fa-caret-down'></i></a>
			<ul id='elNavTheme_menu' class='ipsMenu ipsMenu_selectable ipsHide'>
			{{foreach $themes as $id => $set }}
				{{if $set->canAccess()}}
					<li class='ipsMenu_item{{if \IPS\Theme::i()->id == $id}} ipsMenu_itemChecked{{endif}}'>
						<form action="{url="app=core&module=system&controller=theme" noprotocol="true" csrf="true" seoTemplate="theme"}" method="post">
						<button type='submit' name='id' value='{$id}' class='ipsButton ipsButton_link'>{lang="$set->_title"} {{if $set->is_default}}{lang="default"}{{endif}}</button>
						</form>
					</li>
				{{endif}}
			{{endforeach}}
			</ul>
		</li>
	{{endif}}
	{{if \IPS\Settings::i()->privacy_type != "none"}}
		<li><a href='{{if \IPS\Settings::i()->privacy_type == "internal"}}{url="app=core&module=system&controller=privacy" seoTemplate="privacy"}{{else}}{setting="privacy_link"}{{endif}}'>{lang="privacy"}</a></li>
	{{endif}}
	{{if \IPS\Member::loggedIn()->member_id }}
	<li><a href="http://meat-expert.ru/forms/7-obratnaya-svyaz/">{lang="contact"}</a></li>
	{{endif}}
  <div id="veilonCopyright">
    <a href="/about_eng/"><img src='/images/eng.png' height='30'></a>
    <img src='{resource="mastercard-transparent.png" app="forums" location="front"}' height='30'>
    <img src='{resource="visa-footer.png" app="forums" location="admin"}' height='15'>
  </div>
</ul>	
{{if \IPS\Dispatcher::i()->application instanceof \IPS\Application AND \IPS\Dispatcher::i()->application->canManageWidgets()}}
	<button type='button' id='elWidgetControls' data-action='openSidebar' data-ipsTooltip title='{lang="manage_blocks"}' class='ipsButton ipsButton_primary ipsButton_narrow'><i class='fa fa-chevron-right'></i></button>
{{endif}}
{{endif}}