<ips:template parameters=" " />
{{if \IPS\Theme::i()->logo['front']['url'] !== null }}
{{$logo = \IPS\File::get( 'core_Theme', \IPS\Theme::i()->logo['front']['url'] )->url;}}
<div class="logo">
  <ul class="ipsList_inline ipsType_center ipsList_reset">
    <li class="ipsResponsive_inlineBlock ipsPadhalf" style="margin: 0px;">
		<a href='{setting="base_url"}' id='elLogo' accesskey='1'>
          <img src='{resource="logo_header.png" app="core" location="front"}' class="ipsImage ipsContained"></a>
	</li>
    <li class="ipsResponsive_inlineBlock me-np" style="margin: 0px;">
		<a href="{setting="base_url"}"><img src='{resource="logo_desc.png.a46f9b40c40c3f901e53307ca9eb822b.png" app="forums" location="front"}' class="ipsImage ipsContained"></a>
	</li>
  </ul>
</div>
{{else}}
<a href='{setting="base_url"}' id='elSiteTitle' accesskey='1'>{setting="board_name"}</a>
{{endif}}