<ips:template parameters="" />
<div id="footer_blocks" class="ipsLayout_container clearfix clear">
				<div id="contact_us" class="footer_blocks_content">		
					<div id="footer_block1">
						<h3>Контактная информация портала</h3>
						<ul><noindex>
							<li>Всегда рады вашему звонку:</li>
							<li>+7 (499) 755-67-85</li>
							<li>с 10:00 до 19:00 пн-пт (время московское)</li>
							<li>Мы не торгуем мясом и кишками!</li>
</noindex>
						</ul>
					</div>
					<div id="footer_block2">
						<h3>Контакты специалистов</h3>
						<ul>
							<li>Главный технолог - expert@meat-expert.ru</li>
							<li>Отдел рекламы - reklama@meat-expert.ru</li>
							<li>Отдел новостей - news@meat-expert.ru</li>
							<li>Кадровое агентство - rabota@meat-expert.ru</li>
						</ul>
					</div>
					<div id="footer_block3">
						<div class="right">
							<h2>Copyright © 2005-2016 Независимый портал «Мясной Эксперт»</h2>
<h1>Мясной Эксперт ® - зарегистрированная торговая марка.</h1>
							<ul class="noprint">
								<li><a href="http://www.meat-expert.ru/index.php?app=forums&module=extras&section=boardrules">Правила и положения форума</a></li>
								<li><a rel="nofollow" href="http://www.meat-expert.ru/privacypolicy/">Privacy Policy / Политика конфиденциальности</a></li>
							</ul>
							<ul id="soclinks" class="ipsList_inline">
								<li class="right"><a rel="nofollow" href="http://vk.com/meat_expert"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li class="right"><a rel="nofollow" href="http://vk.com/meat_expert"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
								<li class="right"><a rel="nofollow" href=""><i class="fa fa-rss" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>